### ISSUE TITLE
Misconfiguration in gracefully stopping the scheduler buildbot-master

### ISSUE THREAD

**Issue by MihaiTabara** [hwine/innodb-cutover#3]
(buildduty-tools)[buildduty@buildduty-tools.srv.releng.usw2.mozilla.com maintenance]$ ./manage_masters.py -f ../maintenance/production-masters.json -R scheduler graceful_stop
[buildbot-master81.bb.releng.scl3.mozilla.com] put: /home/buildduty/buildduty-tools/repos/tools/buildfarm/maintenance/buildbot-wrangler.py -> /builds/buildbot/build_scheduler/buildbot-wrangler.py
[buildbot-master81.bb.releng.scl3.mozilla.com] run: rm -f *.pyc
Failed to run graceful_stop on bm81-build_scheduler
Traceback (most recent call last):
  File "./manage_masters.py", line 33, in run_action_on_master
    action_func(master)
  File "/home/buildduty/buildduty-tools/repos/tools/lib/python/util/fabric/actions.py", line 194, in action_graceful_stop
    (master['master_dir'], master['http_port']), workdir=master['basedir'])
KeyError: 'http_port'

I suspect there's some misconfiguration somewhere. Will have a look.

**Comment by nthomas-mozilla** [comment]
A graceful_stop relies on a web interface to do a POST too, which neither scheduler master has. Maybe there is a specific signal we can send instead, otherwise our options are 'do nothing' or treat it as a stop instead.

**Comment by hwine** [comment]
Looks like updated documentation will resolve this.
